routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index')->name('init');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Routes del Sistema
Route::middleware(['auth'])->group(function(){
   
    /*------------------------------------------
     Deficion de Rutas para los Roles del Sistema
     -------------------------------------------- */
    Route::resource('roles', 'RoleController');
    /*------------------------------------------
     Deficion de Rutas para los Usuarios del Sistema
     -------------------------------------------- */
    Route::resource('users', 'UserController');
    /*------------------------------------------
     Deficion de Rutas para los Post del Sistema
     -------------------------------------------- */
    Route::resource('posts', 'PostsController');
});

resources/views/blogpartial/BlogHomePageV5.blade.php
<!--Grid column-->
<div class="col-md-6 mb-4">
    <!--Card-->
    <div class="card text-left">

        <!--Card image-->
        <div class="view overlay">
            {{-- @foreach($post->photos as $photo)
                <img class="img-responsive blog__mxh"
                     src="{{ asset('/storage/' . $photo->url) }}"
                     alt="{{ config('constant.BLOGUERO') }} - {{$post->title}}">
            @endforeach

            <a>
                <div class="mask rgba-white-slight"></div>
            </a> --}}
            @include( $post->viewType() )
        </div>
        <!--/.Card image-->

        <!--Card content-->
        <div class="card-body mx-4">
            <a href="" class="teal-text text-center text-uppercase font-small">
                <h6 class="mb-3 mt-3"> hashtag: <p>
                        @foreach( $post->tags as $tag )
                            @if ($tag->count() > 0)
                                <a href="{{ route('tags.show', $tag) }}">
                                    <strong> #{{ $tag->name }} </strong>
                                </a>
                            @endif
                        @endforeach
                        <br>
                        <hr>
                        <p>Escrito por:
                            <a rel="bookmark"
                               href="{{ route::has('pages.about') }}">{{ config('constant.BLOGUERO') }}</a>, <br>
                    <a class="dark-grey-text font-small"> el {{ $post->created_at->diffForHumans() }}</a>
                        </p>
                </h6>
            </a>
            <!--Title-->
            <h4 class="card-title">
                <strong>{{$post->title}}</strong>
            </h4>
            <hr>
            <!--Text-->
            <p class="dark-grey-text mb-4">{{$post->excerpt}}.</p>

            <p class="text-right mb-0 text-uppercase font-small spacing font-weight-bold">
                <a rel="bookmark"
                   href="{{ route('posts.show', $post) }}">Leer más
                    <i class="fa fa-chevron-circle-right" aria-hidden="true"></i>
                </a>
            </p>
            @include('partials.social-links', ['description' => $post->title])
        </div>
        <!--/.Card content-->

    </div>
    <!--/.Card-->

</div>
<!--Grid column-->

resources/views/blogpartial/BlogListingV4.blade.php
<article class="blog-general">
    <!--Featured image-->
    {{-- @foreach($post->photos as $photo)
    <a rel="bookmark" href="{{ route('posts.show', $post) }}">
    <img src="{{ asset('/storage/' . $photo->url) }}" 
    alt="{{ config('constant.BLOGUERO') }} - {{$post->title}}" class="view overlay rounded z-depth-2 img-fluid">
    </a>
    @endforeach --}}
    @include( $post->viewType() )
    <!--Post data-->
    <div class="text-center my-5">
        <h2>
            <a rel="bookmark" href="{{ route('posts.show', $post) }}" class="font-weight-bold">{{$post->title}}</a>
        </h2>
        <p>Escrito por:
            <a rel="bookmark" href="{{ route::has('pages.about') }}">{{ config('constant.BLOGUERO') }}</a>, {{
            $post->created_at->diffForHumans() }}
        </p>
        <!--Social shares-->
        @include('partial.social-links', ['description' => $post->title])
        <!--Social shares-->
    </div>
        {{$post->excerpt}}
        <p class="text-right mb-0 text-uppercase font-small spacing font-weight-bold">
            <a rel="bookmark" href="{{ route('posts.show', $post) }}">Leer más
                <i class="fa fa-chevron-circle-right" aria-hidden="true"></i>
            </a>
        </p>
</article>

resources/views/blogpartial/BlogSecV1.blade.php
<div class="row bg-white">
        <!--Grid column-->
        <div class="col-lg-5 col-xl-5 pb-3">
            <!--Featured image-->
            <div class="view overlay rounded z-depth-2">
                @foreach($post->photos as $photo)
                    <img src="{{ asset('/storage/' . $photo->url) }}"
                         alt="{{ config('constant.BLOGUERO') }} - {{$post->title}}"
                         class="img-fluid">
                @endforeach
                <a>
                    <div class="mask rgba-white-slight"></div>
                </a>
            </div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-7 col-xl-7">
            <!--Excerpt-->
            <p class="tags"><i class="icon-tags"></i>
            @foreach( $post->tags as $tag )
                @if ($tag->count() > 0)
                        {{-- <a href="{{ route('tags.show', $tag) }}">
                            <strong> #{{ $tag->name }} </strong>
                        </a> --}}
                        <a href="{{ route('tags.show', $tag) }}" rel="tag">{{ $tag->name }}</a> 
                @endif
            @endforeach
        </p>

            <h3 class="mb-4 font-weight-bold lecomp-color">
                <strong>{{$post->title}}</strong>
            </h3>
            <p>
                {!!$post->excerpt!!}.
            </p>
            <p> by
            <a rel="bookmark" href="{{ route::has('pages.about') }}"> {{ config('constant.BLOGUERO') }}
            </a>, <br>
                <a class="dark-grey-text font-small"> el {{ $post->created_at->diffForHumans() }}</a>
            </p>
            <p class="text-right mb-0 text-uppercase font-small spacing font-weight-bold">
                <a rel="bookmark"
                   href="{{ route('posts.show', $post) }}">Leer más
                    <i class="fa fa-chevron-circle-right" aria-hidden="true"></i>
                </a>
                @include('partials.social-links', ['description' => $post->title])
            </p>
        </div>
        <!--Grid column-->
</div>

resources/views/blogpartial/BlogSecV2.blade.php
<div class="row bg-white">
        <!--Grid column-->
        <div class="col-lg-12 col-xl-12">
            <!--Excerpt-->
            <p class="tags"><i class="fa fa-tags"></i>
                @foreach( $post->tags as $tag )
                    @if ($tag->count() > 0)
                            {{-- <a href="{{ route('tags.show', $tag) }}">
                                <strong> #{{ $tag->name }} </strong>
                            </a> --}}
                            <a href="#" rel="tag">{{ $tag->name }}</a> 
                    @endif
                @endforeach
            </p>

            <h3 class="mb-4 font-weight-bold lecomp-color">
                <strong>{{$post->title}}</strong>
            </h3>
            <p>
                {!!$post->excerpt!!}.
            </p>
            <p> by
            <a rel="bookmark" href="{{ route::has('pages.about') }}"> {{ config('constant.BLOGUERO') }}
            </a>, <br>
                <a class="dark-grey-text font-small"> el {{ $post->created_at->diffForHumans() }}</a>
            </p>
            <p class="text-right mb-0 text-uppercase font-small spacing font-weight-bold">
                <a rel="bookmark"
                   href="{{ route('posts.show', $post) }}">Leer más
                    <i class="fa fa-chevron-circle-right" aria-hidden="true"></i>
                </a>
                @include('partial.social-links', ['description' => $post->title])
            </p>
        </div>
        <!--Grid column-->
</div>