routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index')->name('init');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Routes del Sistema
Route::middleware(['auth'])->group(function(){
   
    /*------------------------------------------
     Deficion de Rutas para los Roles del Sistema
     -------------------------------------------- */
    Route::resource('roles', 'RoleController');
    /*------------------------------------------
     Deficion de Rutas para los Usuarios del Sistema
     -------------------------------------------- */
    Route::resource('users', 'UserController');
    /*------------------------------------------
     Deficion de Rutas para los Post del Sistema
     -------------------------------------------- */
    Route::resource('posts', 'PostsController');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Carbon\Carbon;


class Post extends Model
{
    protected $fillable = [
        'title', 'body', 'url', 'iframe', 'excerpt', 'published_at', 'category_id', 'user_id','tipo'
    ];

    protected $dates = ['published_at'];
    //protected $with = ['category', 'tags', 'owner', 'photos'];

    protected static function boot()
    {
        parent::boot();

        static::deleting(function ($post)
        {
            
            $post->tags()->detach();
            if(!empty($post->photo)){
                foreach ($post->photo as $photo) {
                    $photo->delete();
                }
            }
            
        });
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /*sobreescribo o cambio de metodo de busqueda de Id a titulo del post*/

    public function getRouteKeyName()
    {
        return 'url';
    }


    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function user(){
        return $this->belongsTo(User::class,'user_id','id');
    }

    public function comments(){
        return $this->hasMany(Comment::class,'post_id','id');
    }

    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function scopePublished($query)
    {
        $request = request();

        $query->with(['category', 'tags', 'owner', 'photos'])
            ->whereNotNull('published_at')
            ->where('published_at', '<=', Carbon::now())
            ->orderBy('published_at' , 'DESC')
            ->get();

        if($request->year) {
            $query->whereYear('published_at', $request->year);
        }

        if($request->month) {
            $query->whereMonth('published_at', $request->month);
        }
    }

    public function scopeBlogPublished($query)
    {
        $request = request();

        $query->with(['category', 'tags', 'owner'])
            ->whereNotNull('published_at')
            ->where('published_at', '<=', Carbon::now())
            ->latest('published_at')
            ->get();

        if($request->year) {
            $query->whereYear('published_at', $request->year);
        }

        if($request->month) {
            $query->whereMonth('published_at', $request->month);
        }
        if($request->title) {
            $query->where('title', 'LIKE', "%$request->title%");
        }
    }

    public function scopeAllowed($query)
    {
        if ( auth()->user()->can('view', $this) )
        {
            $posts = $query;
        }
        else
        {
            $posts = $query->where('user_id', auth()->id());
        }
    }

    public function isPublished()
    {
        return ! is_null($this->published_at) && $this->published_at < Carbon::today();
    }

    public static function create(array $attributes = [])
    {
        $attributes['user_id'] = auth()->id();
        /*--------------------------------------------------
        Modificacion de la forma de como se guarda los post 
        a la forma tradicional
        ----------------------------------------------------- */
        $post = new Post();
        $post->title = $attributes['title'];
        $post->user_id = $attributes['user_id'];
        $post->generateUrl();
        return $post;
    }

    public function generateUrl()
    {
        $url = str_slug($this->title);

        if ($this->whereUrl($url)->exists())
        {
            $url = "{$url}-{$this->id}";
        }
        $this->url = $url;

        $this->save();
    }

    public function scopeByYearAndMonth($query)
    {
        return $query->selectRaw('year(published_at) year')
            ->selectRaw('month(published_at) month')
            ->selectRaw('monthname(published_at) monthname')
            ->selectRaw('count(*) posts')
            ->groupBy('year', 'month', 'monthname', 'published_at')
            ->orderBy('year', 'month');
    }

    /*Metodo Mutador de Fecha de Publicacion*/
    public function setPublishedAtAttribute($published_at)
    {
        $this->attributes['published_at'] = $published_at ? Carbon::parse($published_at) : null;
    }

    /*Metodo Mutador de Categorias*/
    public function setCategoryIdAttribute($category)
    {
        $this->attributes['category_id'] = Category::find($category)
            ? $category
            : Category::create(['name' => $category])->id;
    }

    /*Funcion normal Synctags*/

    public function syncTags($tags)
    {       
        /* se cambio para que los tag fueran int para la sincronizacion */
        $tagIds = collect($tags)->map(function ($tag) {
            return Tag::find($tag) ? $tag : (string) Tag::create(['name' => $tag])->id;
        });
        return $tagIds;
    }

    public function viewType($home = '')
    {
        if($this->iframe):
            return 'posts.iframe';
        endif;
        return 'posts.text';
    

    }
    public function viewPostType($home = '')
    {
        if($this->iframe):
            return 'homePosts.iframe';
        endif;
        if($this->photos->count() === 1):
            return 'homePosts.photo';
        elseif($this->photos->count() > 1):
            return $home === 'home' ? 'homePosts.carousel-preview' : 'homePosts.carousel' ;
        else:
            return 'homePosts.text';
        endif;

    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\StorePostRequest;
use Illuminate\Http\Request;
use App\Post;
use App\Tag;
use Laracasts\Flash\Flash;

class PostsController extends Controller
{
    public function index()
    {
        $posts = Post::paginate(15);
        // return $posts;
    	return view('admin.posts.index', compact('posts'));
    }

    public function store(Request $request)
    {
        $this->validate($request, ['title' => 'required|min:3']);
        $post = Post::create( $request->except(['_token']) );
        return redirect()->route('posts.edit', $post);
    }

    public function edit(Post $post)
    {      
        return view('admin.posts.edit', [
            'post' => $post,
            'tags' => Tag::all(),
            'categories' => Category::all()
        ]);
    }


    public function show(Post $post)
    {
              
        if($post->isPublished() || auth()->check())
        {
            return view('posts.show', compact('post'));
        }
        abort(404);
    }

    public function update(Post $post, StorePostRequest $request)
    {
         $post->update($request->all());
        $tagss=$request->input('tags');
        $tags=array();
        foreach($tagss as $tag){
            $temp=Tag::find($tag) ? $tag : (string) Tag::create(['name' => $tag])->id;
            array_push($tags,$temp);
        }
        $post->tags()->sync( $tags);
        Flash::success('La publicación ha sido guardada.');
        return redirect()
            ->route('posts.index', $post);
    }

    public function destroy(Post $post)
    {
        $post->delete();
        Flash::success('La publicación ha sido eliminada');
        return redirect()
            ->route('posts.index');
    }
}

resources/views/admin/posts/create-bck.blade.php
@extends('admin.layout')
@push('styles')
    {{--Select 2 --}}
    <link rel="stylesheet"
          href="{{ asset('/plugins/admin/vendors/bower_components/select2/dist/css/select2.min.css') }}">
    {{--date--}}
    <link rel="stylesheet"
          href="{{ asset('/plugins/admin/vendors/bower_components/flatpickr/dist/flatpickr.min.css') }}">
    {{--Summernote--}}
    <link rel="stylesheet" href="{{ asset('plugins/admin/vendors/bower_components/summernote/summernote-bs4.css')}}">
@endpush
@section('header')
    <header class="content__title">
        <h1>{{ config('constant.BLOGUERO') }} </h1>
        {{--<small> Crear Posts</small>--}}
        <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Inicio</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.admin.posts.index') }}">Posts</a></li>
                <li class="breadcrumb-item active" aria-current="page">Crear post</li>
            </ol>
        </nav>
        {{--<h4 class="card-title">Crear publicación</h4>--}}
        <div class="actions">
            <a href="" class="actions__item zmdi zmdi-trending-up"></a>
            <a href="" class="actions__item zmdi zmdi-check-all"></a>

            <div class="dropdown actions__item">
                <i data-toggle="dropdown" class="zmdi zmdi-more-vert"></i>
                <div class="dropdown-menu dropdown-menu-right">
                    <a href="" class="dropdown-item">Refresh</a>
                    <a href="" class="dropdown-item">Manage Widgets</a>
                    <a href="" class="dropdown-item">Settings</a>
                </div>
            </div>
        </div>

    </header>
@stop

@section('content')
    {{--WEB--}}
    <form class="row" method="POST" action="{{ route('admin.admin.posts.store') }}" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{--<div class="row">--}}

        <div class="col-lg-8 col-md-7">
            <div class="card">
                <div class="card-body">
                    <div class="form-group {{ $errors->has('title') ? 'has-warning' : '' }}">
                        <h4 class="card-title">Título de la publicación</h4>
                        <input name="title"
                               value="{{old('title')}}"
                               class="form-control textarea-autosize text-counter"
                               data-max-length="45"
                               data-min-length="10"
                               placeholder="(Max cantidad de caracteres 45)"/>
                        {{ $errors->first('title'), '<span class="help-block">:message</span>' }}
                        <i class="form-group__bar"></i>
                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    <div class="form-group {{ $errors->has('body') ? 'has-warning' : '' }}">
                        <h4 class="card-title">Contenido completo de la publicación</h4>
                        <textarea name="body"
                                  id="summernote"
                                  rows="10"
                                  class="form-control"
                                  placeholder="Hola {{ auth()->user()->name }}, ya puedes iniciar... ">
                            {{old('body')}}
                        </textarea>
                        {{ $errors->first('body'), '<span class="help-block">:message</span>' }}
                        <i class="form-group__bar"></i>
                    </div>
                </div>
            </div>
        </div>
        {{--FIN WEB--}}
        {{--ASIDE--}}
        <div class="col-lg-4 col-md-5 hidden-md-down">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Fecha de publicación</h4>
                    <h6 class="card-subtitle">Si no colocas fecha el post quedara guardado pero no se publicara</h6>
                    <div>
                        {{--<label>Fecha de publicación</label>--}}
                        <div class="input-group mb-2 pb-2">
                                    <span class="input-group-addon">
                                        <i class="zmdi zmdi-calendar"></i></span>
                            <div class="form-group">
                                <input type="date" name="published_at" value="{{old('published_at')}}" class="form-control datetime-picker flatpickr-input"
                                       placeholder="Insertar Fecha" readonly="readonly">
                                <i class="form-group__bar"></i>
                            </div>
                           {{-- <div class="form-group {{ $errors->has('time') ? 'has-warning' : '' }}">
                                <input name="time"  value="{{old('time')}}"  type="time" class="form-control time-picker flatpickr-input"
                                       placeholder="Insertar hora" readonly="readonly">
                                {{ $errors->first('time'), '<span class="help-block">:message</span>' }}
                                <i class="form-group__bar"></i>
                            </div>--}}
                        </div>
                        <div class="form-group mb-3 pb-3 {{ $errors->has('category') ? 'has-warning' : '' }}">
                            <h4 class="card-title">Categoría</h4>

                            <select name="category" class="select2">
                                <option value="">Elegir categoría</option>
                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}"
                                    {{old('category') == $category->id ? 'selected' : '' }}>
                                        {{ $category->name }}
                                    </option>
                                @endforeach
                            </select>
                            {{ $errors->first('category'), '<span class="help-block">:message</span>' }}
                        </div>

                        <div class="form-group mb-3 pb-3 {{ $errors->has('tags') ? 'has-warning' : '' }}">
                            <h4 class="card-title">Etiquetas</h4>

                            <select name="tags[]" class="select2 select2-hidden-accessible" multiple=""
                                    tabindex="-1" aria-hidden="true">

                                @foreach($tags as $tag)
                                    <option {{ collect(old('tags'))->contains($tag->id) ? 'selected' : ''}} value="{{ $tag->id }}">{{ $tag->name }}</option>
                                @endforeach
                            </select><span
                                    class="select2 select2-container select2-container--default select2-container--below"
                                    dir="ltr" style="width: 100%;"><span class="selection"><span
                                            class="select2-selection select2-selection--multiple" role="combobox"
                                            aria-haspopup="true" aria-expanded="false" tabindex="-1"><ul
                                                class="select2-selection__rendered"><li
                                                    class="select2-search select2-search--inline"><input
                                                        class="select2-search__field" type="search" tabindex="0"
                                                        autocomplete="off" autocorrect="off" autocapitalize="off"
                                                        spellcheck="false" role="textbox" aria-autocomplete="list"
                                                        placeholder=""
                                                        style="width: 0.75em;"></li></ul></span></span><span
                                        class="dropdown-wrapper" aria-hidden="true"></span></span>
                            {{ $errors->first('tags'), '<span class="help-block">:message</span>' }}
                        </div>

                        <div class="form-group mt-2 {{ $errors->has('excerpt') ? 'has-warning' : '' }}">
                            <h4 class="card-title">Extracto de la publicación</h4>
                            <textarea
                                    name="excerpt"
                                    class="form-control textarea-autosize text-counter"
                                    data-max-length="275" data-min-length="140"
                                    placeholder="Puedes iniciar... (Max cantidad de caracteres 275 y minimo 140)">
                                {{ old('excerpt') }}
                            </textarea>
                            {{ $errors->first('excerpt'), '<span class="help-block">:message</span>' }}
                            <i class="form-group__bar"></i>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-light btn-block" type="submit">Guardar Publicación</button>
                        </div>
                    </div>

                    {{--<div>
                        <label>Date picker</label>

                        <div class="input-group">
                            <span class="input-group-addon"><i class="zmdi zmdi-calendar"></i></span>
                            <div class="form-group">
                                <input type="text" class="form-control date-picker flatpickr-input" placeholder="Pick a date" readonly="readonly">
                                <i class="form-group__bar"></i>
                            </div>
                        </div>
                    </div>

                    <div>
                        <label>Time picker</label>

                        <div class="input-group">
                            <span class="input-group-addon"><i class="zmdi zmdi-calendar"></i></span>
                            <div class="form-group">
                                <input type="text" class="form-control time-picker flatpickr-input" placeholder="Pick a time" readonly="readonly">
                                <i class="form-group__bar"></i>
                            </div>
                        </div>
                    </div>--}}

                </div>
            </div>
        </div>

        {{--</div>--}}
    </form>

@stop
@push('script')
    {{--create posts--}}
    {{--<script src="{{ asset('/plugins/admin/vendors/bower_components/jquery-mask-plugin/dist/jquery.mask.min.js') }}"></script>--}}
    <script src="{{ asset('/plugins/admin/vendors/bower_components/select2/dist/js/select2.full.min.js') }}"></script>
    {{--<script src="{{ asset('/plugins/admin/vendors/bower_components/dropzone/dist/min/dropzone.min.js') }}"></script>--}}
    {{--<script src="{{ asset('/plugins/admin/vendors/bower_components/moment/min/moment.min.js') }}"></script>--}}
    <script src="{{ asset('/plugins/admin/vendors/bower_components/flatpickr/dist/flatpickr.min.js') }}"></script>
    {{--<script src="{{ asset('/plugins/admin/vendors/bower_components/nouislider/distribute/nouislider.min.js') }}"></script>--}}
    {{--<script src="{{ asset('/plugins/admin/vendors/bower_components/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js') }}"></script>--}}
    {{--<script src="{{ asset('/plugins/admin/vendors/bower_components/trumbowyg/dist/trumbowyg.min.js') }}"></script>--}}
    <script src="{{asset('plugins/admin/vendors/bower_components/summernote/summernote-bs4.js')}}"></script>
    <script src="{{asset('plugins/admin/vendors/bower_components/summernote/summernote-image-title.js')}}"></script>
    <script src="{{asset('plugins/admin/vendors/bower_components/summernote/lang/summernote-es-ES.js')}}"></script>
    <script src="{{ asset('/plugins/admin/vendors/bower_components/tinymce/tinymce.min.js') }}"></script>
    {{--<script src="{{ asset('/plugins/admin/vendors/bower_components/rateYo/min/jquery.rateyo.min.js') }}"></script>--}}
    <script src="{{ asset('/plugins/admin/vendors/bower_components/jquery-text-counter/textcounter.min.js') }}"></script>
    <script src="{{ asset('/plugins/admin/vendors/bower_components/autosize/dist/autosize.min.js') }}"></script>



    James Camomile
    Hace 1 año
    For those like me who like to copy and wish they could copy code from a video:

    <script>
        /*$('#summernote').summernote({
            placeholder: 'Hola ',
            imageTitle: {
                specificAltField: true,
            },
            lang: 'es-ES',
            height: 300,                 // set editor height
            minHeight: null,             // set minimum height of editor
            maxHeight: null,             // set maximum height of editor
            tabsize: 6

        });*/
        $('#summernote').summernote({
            placeholder: 'Hola {{ Auth::user()->name }}',
            imageTitle: {
                specificAltField: true,
            },
            lang: 'es-ES',
            popover: {
                image: [
                    ['imagesize', ['imageSize100', 'imageSize50', 'imageSize25']],
                    ['float', ['floatLeft', 'floatRight', 'floatNone']],
                    ['remove', ['removeMedia']],
                    ['custom', ['imageTitle']],
                ],
            },
            height: 300,                 // set editor height
            minHeight: null,             // set minimum height of editor
            maxHeight: null,             // set maximum height of editor
            tabsize: 6
        });
    </script>﻿
@endpush

resources/views/admin/posts/create.blade.php
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<form method="POST" action="{{ route('posts.store') }}">
		{{ csrf_field() }}
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title" id="myModalLabel">Agrega el título de tu nueva publicación</h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				</div>
				<div class="modal-body">
					<div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
						<label>Título de la publicación</label>
						<input id="post-title" name="title"
						class="form-control"
						value="{{ old('title') }}"
						placeholder="Ingresa aquí el título de la publicación" autofocus required>
						{!! $errors->first('title', '<span class="help-block">:message</span>') !!}
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
					<button class="btn btn-success">Crear publicación</button>
				</div>
			</div>
		</div>
	</form>
</div>

@push('scripts')
	<script>
        if ( window.location.hash === '#create') {
            $('#myModal').modal('show');
        }

        $('#myModal').on('hide.bs.modal', function(){
            window.location.hash = '#';
        });

        $('#myModal').on('shown.bs.modal', function(){
            $('#post-title').focus();
            window.location.hash = '#create';
        });
    </script>
@endpush

resources/views/admin/posts/index.blade.php
@extends('layouts.app')

@section('header')
<h1>
    POSTS
    <small>Listado</small>
</h1>
@stop

@section('content')
<div class="container">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Listado de publicaciones</h3>
            <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#myModal">
                <i class="fa fa-plus"></i> Crear publicación
            </button>
        </div>
        @include('admin.posts.create')
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="posts-table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Título</th>
                        <th>Extracto</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($posts as $post)
                    <tr>
                        <td>{{ $post->id }}</td>
                        <td>{{ $post->title }}</td>
                        <td>{{ $post->excerpt }}</td>
                        <td width="15%">
                            <a href="{{ route('posts.show', $post) }}" class="btn btn-xs btn-success" target="_blank"><i
                                    class="fa fa-eye"></i></a>
                            <a href="{{route('posts.edit',$post)}}" class="btn btn-xs btn-info"><i
                                    class="fa fa-pencil text-white"></i></a>
                            <form method="POST" action="{{ route('posts.destroy',$post) }}" style="display: inline">
                                {{ csrf_field() }} {{ method_field('DELETE') }}
                                <button class="btn btn-xs btn-danger"
                                    onclick="return confirm('¿Estás seguro de querer eliminar esta publicación?')"><i
                                        class="fa fa-times"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
			</table>
			{{ $posts->links() }}
        </div>
        <!-- /.box-body -->
    </div>
</div>
<!-- /.box -->
@stop

@push('styles')
<link rel="stylesheet" href="{{ asset('adminlte/plugins/datatables/dataTables.bootstrap.css') }}">
@endpush

@push('scripts')
<script src="{{ asset('adminlte/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('adminlte/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
<script>
    $(function () {
        $("#posts-table").DataTable();
    });

</script>
@endpush