routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index')->name('init');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Routes del Sistema
Route::middleware(['auth'])->group(function(){
   
    /*------------------------------------------
     Deficion de Rutas para los Roles del Sistema
     -------------------------------------------- */
    Route::resource('roles', 'RoleController');
    /*------------------------------------------
     Deficion de Rutas para los Usuarios del Sistema
     -------------------------------------------- */
    Route::resource('users', 'UserController');
    /*------------------------------------------
     Deficion de Rutas para los Post del Sistema
     -------------------------------------------- */
    Route::resource('posts', 'PostsController');
});

resources/views/usuarios/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <section class="content-header">
                <h1>
                User Registration
                </h1>
            </section>
            <div class="content">
                @include('layouts.errors')
                <div class="box box-primary">
            
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-12">
                            {{ Form::open(['route' => 'users.store','id'=>'formulario','name'=>'formulario']) }}
                                @include('usuarios.fields')
                            {!! Form::close() !!}
                            </div>
                       
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('styles')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@7.33.1/dist/sweetalert2.min.css">
@endpush
@push('scriptsf')
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.33.1/dist/sweetalert2.all.min.js"></script>

@endpush

resources/views/usuarios/datatables_actions.blade.php
{!! Form::open(['route' => ['planillas.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('planillas.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('planillas.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/usuarios/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <section class="content-header">
                <h1>
                    User Update
                </h1>
            </section>
            <div class="content">
                @include('layouts.errors')
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="row" style="display:flex; flex-direction:column; align-items:center;">
                            <div class="col-sm-8">
                                {!! Form::model($user, ['route' => ['users.update', $user], 'method' => 'patch']) !!}
                                    @include('usuarios.fields')
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/usuarios/fields.blade.php
<div class="form-group has-feedback{{ $errors->has('name') ? ' has-error' : '' }}">
    <span class="fa fa-user form-control-feedback"></span>
    <input type="text" class="form-control" name="name" value="{{ old('name',$user->name) }}" placeholder="Full Name">
    @if ($errors->has('name'))
    <span class="help-block">
        <strong>{{ $errors->first('name') }}</strong>
    </span>
    @endif
</div>


<div class="form-group has-feedback{{ $errors->has('email') ? ' has-error' : '' }}">
    <span class="fa fa-envelope form-control-feedback"></span>
    <input type="email" class="form-control" name="email" value="{{ old('email',$user->email) }}" placeholder="Email">

    @if ($errors->has('email'))
    <span class="help-block">
        <strong>{{ $errors->first('email') }}</strong>
    </span>
    @endif
</div>

<div class="form-group has-feedback{{ $errors->has('password') ? ' has-error' : '' }}">
    <span class="fa fa-key form-control-feedback"></span>
    <input type="password" class="form-control" name="password" placeholder="Password" value="">

    @if ($errors->has('password'))
    <span class="help-block">
        <strong>{{ $errors->first('password') }}</strong>
    </span>
    @elseif ($user->name != '')
    <span class="help-block">
        <small style="color:blue; margin-left: 1rem;">leave blank if you do not want to change the password</small>
    </span>
    @endif
</div>

<div class="form-group has-feedback{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
    <span class="fa fa-lock form-control-feedback"></span>
    <input type="password" name="password_confirmation" class="form-control" placeholder="Confirm password" value="">

    @if ($errors->has('password_confirmation'))
    <span class="help-block">
        <strong>{{ $errors->first('password_confirmation') }}</strong>
    </span>
    @endif
</div>


<h3>Lista de Roles</h3>
<div class="form-group">
    <ul class="list-unstyled">
    @foreach ($roles as $role)
    <li>
    <label>
        {{Form::checkbox('roles[]',$role->id,null)}}
        {{$role->name}}
        <em>({{$role->description ?: 'N/A'}})</em>
    </label>
    </li>
    @endforeach
    </ul>
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12" >
    {!! Form::submit('Save', ['class' => 'btn btn-success','id' =>'btnGuardar']) !!}
    <a href="{!! route('users.index') !!}" class="btn btn-danger">Cancel</a>
</div>

resources/views/usuarios/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-8">
            <section class="content-header">
                <h1 class="pull-left">Users Manager</h1>
                <h1 class="pull-right">
                    @can('users.create')
                    <a class="btn btn-success" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('users.create') !!}">Add New</a>
                    @endcan
                </h1>
            </section>
            <div class="content">
                <div class="clearfix"></div>
        
                @include('flash::message')
        
                <div class="clearfix"></div>
                <div class="box box-primary">
                    <div class="box-body">
                            @include('usuarios.table')
                    </div>
                </div>
                <div class="text-center">
                
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/usuarios/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <section class="content-header">
                <h1>
                    Users Show
                </h1>
            </section>
            <div class="content">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="container">
                            <div class="row justify-content-center">
                                @include('usuarios.show_fields')
                                <div class="col-sm-12">
                                    <a href="{!! route('users.index') !!}" class="btn btn-danger">Back</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/usuarios/show_fields.blade.php
<!-- Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $user->id !!}</p>
</div>

<!-- Customername Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fulname', 'Name:') !!}
    <p>{!! $user->name !!}</p>
</div>

<!-- Date Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    <p>{!! $user->email !!}</p>
</div>


<!-- Created At Field -->
<div class="form-group col-sm-6">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $user->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group col-sm-6">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $user->updated_at !!}</p>
</div>

resources/views/usuarios/table.blade.php
<div class="table-responsive">
    <table class="table table-responsive datatable" id="example1">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Roles</th>
                <th colspan="3">Option</th>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
            <tr>
                <td>{{ $user->id }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td width="20%">{{ $user->getRoleName() }}</td>
                <td>
                    @can('users.show')
                    <a href="{{ route('users.show', $user)}}" class="btn btn-xs btn-success"><i class="fa fa-eye"></i></a>
                    @endcan
                    @can('users.edit')
                    <a href="{{ route('users.edit', $user)}}" class="btn btn-xs btn-info"><i class="fa fa-pencil text-white"></i></a>
                    @endcan
                    @can('users.destroy')
                    <form method="POST" action="{{ route('users.destroy', $user) }}" style="display: inline">
                        {{ csrf_field() }} {{ method_field('DELETE') }}
                        <button class="btn btn-xs btn-danger" onclick="return confirm('You are sure to Remove this User?')">
                            <i class="fa fa-trash"></i>
                        </button>
                    </form>
                    @endcan
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    {{ $users->links() }}

</div>
@push('styles')
@include('layouts.datatables_css')

@endpush

@push('scriptsf')
@include('layouts.datatables_js')

<script>

</script>
@endpush

resources/views/usuarios/verify.blade.php
@extends('layouts.app')
@push('styles')
<style>
    .form-group{
        display:flex;
        margin-bottom:0.2rem;   
    }
    .form-group label{
        margin-right:1rem;
    }
    .botones{
        margin-top:1rem;
    }
    .botones .btn{
        margin-right:1rem;
    }
  
</style>
@endpush
@section('content')
<section class="content-header">
    <h1>
        Transfer verification
    </h1>
</section>
<div class="content">
    <!-- @include('adminlte-templates::common.errors') -->
    <div class="box box-primary">

        <div class="box-body">
            <div class="container">
                <div class="row">
                    <!-- Id Field -->
                    <div class="col-sm-6">
                        <div class="form-group">
                            {!! Form::label('id', 'Form:') !!}
                            <p>{!! $planilla->id !!}</p>
                        </div>
                        <!-- Customername Field -->
                        <div class="form-group">
                            {!! Form::label('customerName', 'Customer Name:') !!}
                            <p>{!! $planilla->customerName !!}</p>
                        </div>

                        <!-- Date Field -->
                        <div class="form-group">
                            {!! Form::label('date', 'Date:') !!}
                            <p>{!! $planilla->date !!}</p>
                        </div>

                        <!-- Accountnumber Field -->
                        <div class="form-group">
                            {!! Form::label('accountnumber', 'Account Number:') !!}
                            <p>{!! $planilla->accountnumber !!}</p>
                        </div>

                        <!-- Customeraddress Field -->
                        <div class="form-group">
                            {!! Form::label('customeraddress', 'Customer Address:') !!}
                            <p>{!! $planilla->customeraddress !!}</p>
                        </div>

                        <!-- City Field -->
                        <div class="form-group">
                            {!! Form::label('city', 'City:') !!}
                            <p>{!! $planilla->city !!}</p>
                        </div>
                        <!-- State Field -->
                        <div class="form-group">
                            {!! Form::label('state', 'State:') !!}
                            <p>{!! $planilla->state !!}</p>
                        </div>

                        <!-- Zip Field -->
                        <div class="form-group">
                            {!! Form::label('zip', 'Zip:') !!}
                            <p>{!! $planilla->zip !!}</p>
                        </div>

                        <!-- Country Field -->
                        <div class="form-group">
                            {!! Form::label('country', 'Country:') !!}
                            <p>{!! $planilla->country !!}</p>
                        </div>

                        <!-- Amount Field -->
                        <div class="form-group">
                            {!! Form::label('amount', 'Amount:') !!}
                            <p>{!! $planilla->amount !!}</p>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <!-- Currency Field -->
                        <div class="form-group">
                            {!! Form::label('currency', 'Currency:') !!}
                            <p>{!! $planilla->currency !!}</p>
                        </div>

                        <!-- Othercurrency Field -->
                        <div class="form-group">
                            {!! Form::label('Othercurrency', 'Other Currency:') !!}
                            <p>{!! $planilla->Othercurrency !!}</p>
                        </div>

                        <!-- Intermediary Field -->
                        <div class="form-group">
                            {!! Form::label('intermediary', 'Intermediary Bank Name:') !!}
                            <p>{!! $planilla->intermediary !!}</p>
                        </div>

                        <!-- Aba Field -->
                        <div class="form-group">
                            {!! Form::label('aba', 'A.B.A:') !!}
                            <p>{!! $planilla->aba !!}</p>
                        </div>

                        <!-- Iban Field -->
                        <div class="form-group">
                            {!! Form::label('iban', 'IBAN:') !!}
                            <p>{!! $planilla->iban !!}</p>
                        </div>

                        <!-- Swift Field -->
                        <div class="form-group">
                            {!! Form::label('swift', 'Swift:') !!}
                            <p>{!! $planilla->swift !!}</p>
                        </div>

                        <!-- Countryi Field -->
                        <div class="form-group">
                            {!! Form::label('countryi', 'Country:') !!}
                            <p>{!! $planilla->countryi !!}</p>
                        </div>

                        <!-- Beneficiarybankname Field -->
                        <div class="form-group">
                            {!! Form::label('BeneficiaryBankName', 'Beneficiary Bank Name:') !!}
                            <p>{!! $planilla->BeneficiaryBankName !!}</p>
                        </div>

                        <!-- Bankstreetaddress Field -->
                        <div class="form-group">
                            {!! Form::label('Bankstreetaddress', 'Bankstreet Address:') !!}
                            <p>{!! $planilla->Bankstreetaddress !!}</p>
                        </div>

                        <!-- Cityb Field -->
                        <div class="form-group">
                            {!! Form::label('cityb', 'City:') !!}
                            <p>{!! $planilla->cityb !!}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="box box-primary">

        <div class="box-body">
            <div class="container">
                <div class="row">
                        <div class="col-sm-6">
                            <!-- Stateb Field -->
                            <div class="form-group">
                                {!! Form::label('stateb', 'State:') !!}
                                <p>{!! $planilla->stateb !!}</p>
                            </div>

                            <!-- Zipb Field -->
                            <div class="form-group">
                                {!! Form::label('zipb', 'Zip:') !!}
                                <p>{!! $planilla->zipb !!}</p>
                            </div>

                            <!-- Countryb Field -->
                            <div class="form-group">
                                {!! Form::label('countryb', 'Country:') !!}
                                <p>{!! $planilla->countryb !!}</p>
                            </div>

                            <!-- Beneficiaryname Field -->
                            <div class="form-group">
                                {!! Form::label('BeneficiaryName', 'Beneficiary Name:') !!}
                                <p>{!! $planilla->BeneficiaryName !!}</p>
                            </div>

                            <!-- Beneficiaryaccount Field -->
                            <div class="form-group">
                                {!! Form::label('BeneficiaryAccount', 'Beneficiary Account:') !!}
                                <p>{!! $planilla->BeneficiaryAccount !!}</p>
                            </div>

                            <!-- Beneficiaryaddress Field -->
                            <div class="form-group">
                                {!! Form::label('BeneficiaryAddress', 'Beneficiary Address:') !!}
                                <p>{!! $planilla->BeneficiaryAddress !!}</p>
                            </div>

                            <!-- Citybe Field -->
                            <div class="form-group">
                                {!! Form::label('citybe', 'City:') !!}
                                <p>{!! $planilla->citybe !!}</p>
                            </div>

                            <!-- Statebe Field -->
                            <div class="form-group">
                                {!! Form::label('statebe', 'State:') !!}
                                <p>{!! $planilla->statebe !!}</p>
                            </div>

                            <!-- Zipbe Field -->
                            <div class="form-group">
                                {!! Form::label('zipbe', 'Zip:') !!}
                                <p>{!! $planilla->zipbe !!}</p>
                            </div>

                            <!-- Countrybe Field -->
                            <div class="form-group">
                                {!! Form::label('countrybe', 'Country:') !!}
                                <p>{!! $planilla->countrybe !!}</p>
                            </div>
                        </div>
                        <div class="col-sm-6">

                            <!-- Finalbeneficiary Field -->
                            <div class="form-group">
                                {!! Form::label('finalbeneficiary', 'Final Beneficiary Name:') !!}
                                <p>{!! $planilla->finalbeneficiary !!}</p>
                            </div>

                            <!-- Accountnumberf Field -->
                            <div class="form-group">
                                {!! Form::label('accountnumberf', 'Account Number:') !!}
                                <p>{!! $planilla->accountnumberf !!}</p>
                            </div>

                            <!-- Wiretransferreference Field -->
                            <div class="form-group">
                                {!! Form::label('wiretransferreference', 'Wire Transfer Reference:') !!}
                                <p>{!! $planilla->wiretransferreference !!}</p>
                            </div>

                            <!-- Especialinstruccions Field -->
                            <div class="form-group">
                                {!! Form::label('especialinstruccions', 'Especial Instruccions:') !!}
                                <p>{!! $planilla->especialinstruccions !!}</p>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>

    <div class="box box-primary">

        <div class="box-body">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        {{ Form::open(['route' => 'planilla.verificacion','id'=>'formulario','name'=>'formulario']) }}
                        <h2>Transfer Verification</h2>
                        <div class="form-check">
                            <label>
                                <input type="checkbox" name="fiserv" value="">
                                <span class="label-text">Do the name and acount numbers match
                                    with the ones registered on Fiserv?</span>
                            </label>
                        </div>
                        <div class="form-check">
                            <label>
                                <input type="checkbox" name="email" value="">
                                <span class="label-text">Does the email match with the one registered?</span>
                            </label>
                        </div>
                        <div class="form-check">
                            <label>
                                <input type="checkbox" name="money" value="">
                                <span class="label-text">Is the money available?</span>
                            </label>
                        </div>
                        <div class="form-check">
                            <label>
                                <input type="checkbox" name="number" value="">
                                <span class="label-text">Are the A.B.A and swift numbers correct?</span>
                            </label>
                        </div>
                        <div class="form-check">
                            <label>
                                <input type="checkbox" name="direccion" value="">
                                <span class="label-text">Is the information complete including name an address?</span>
                            </label>
                        </div>
                        <div class="form-group botones col-sm-12">
                            {!! Form::submit('Save', ['class' => 'btn btn-success','id' =>'btnGuardar']) !!}
                            <a href="{!! route('planillas.index') !!}" class="btn btn-danger">Cancel</a>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
        <!-- Submit Field -->
        
    </div>
</div>
@endsection